#correct classpath
server:
  port: 8080
  servlet:
    context-path: /chen

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true   #Enable Rest functionality for the page form
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/myblog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    hikari:
      auto-commit: false
  servlet:
    multipart:  #文件大小限制
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    #username: 1345305701@qq.com
    #password: hnikomyarhtkicha
    #host: smtp.qq.com
    # qq需要配置ssl
    properties:
      mail:
        smtp:
          ssl:
            enable: true


#别名
mybatis:
  type-aliases-package: com.chen.pojo
  configuration:
    #111
    map-underscore-to-camel-case: true



index:
  static:
    properties:
      myEmail: 506337889@qq.com #我的邮箱
      everyPageTopicCount: 5 # 首页每页的topic数量
      topicRankCount: 10      # topic热度排行的数量
      topicNearCount: 10      # topic最新发布榜的数量
      hotUserCount: 5        # 热评用户榜的数量
      showFansCount: 10     #一页展示的fans数量
      showMessageCount: 5  #展示信息的数量
      avatar: /www/wwwroot/images/avatar/  # 头像路径
      topicPicture: /www/wwwroot/images/topicPicture/ #帖子封面路径
      otherPicture: /www/wwwroot/images/other/ #其他图片路径
      tagCount: 10
