#correct classpath
server:
  port: 8080
  servlet:
    context-path: /chen

spring:
  mvc:
    hidden-method:
      filter:
        enabled: true   #Enable Rest functionality for the page form
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/game?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource # Custom data sources
#    hikari:
#      auto-commit: false
  servlet:
    multipart:  #File size limit
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    #username: 1345305701@qq.com
    #password: hnikomyarhtkicha
    #host: smtp.qq.com
    # qq needs ssl
    properties:
      mail:
        smtp:
          ssl:
            enable: true



#别名
mybatis:
  type-aliases-package: com.chen.pojo
  configuration:
    #下划线转驼峰
    map-underscore-to-camel-case: true



index:
  static:
    properties:
      myEmail: tang-h@ulster.ac.uk #email
      everyPageTopicCount: 5 # topic quantity
      topicRankCount: 10      # topic quantity
      topicNearCount: 10      # topic latest rank
      hotUserCount: 5        # pop topic quantity
      showFansCount: 5     #per page fans
      showMessageCount: 5  #ins quantity
      avatar: D:/Program Files/JetBrains/IDEAPro/YobroGames/src/main/resources/static/images/avatar/  # img path
      topicPicture: D:/Program Files/JetBrains/IDEAPro/YobroGames/src/main/resources/static/images/topicPicture/ #topic img path
      otherPicture:  #route for other
      tagCount: 10


